### ISSUE TITLE
催更啊！

### ISSUE THREAD

**Issue by qzlu-cyber** [MountPOTATO/Software-Engineering-Notes#4]
研究生复试，黑皮书看不懂，要靠这个救命了

**Comment by MountPOTATO** [comment]
> 研究生复试，黑皮书看不懂，要靠这个救命了

十分抱歉，关于黑书后面部分对软件测试和软件管理的介绍，学院的课纲里不采用黑书，我们也才开始学。给你找了份学校软件测试的材料不知道能不能派上用场，不过也只是和黑书对应内容相似。链接: https://pan.baidu.com/s/1asPkwkWD-Tm7Gi3TU9VtmA 提取码: m384

**Comment by qzlu-cyber** [comment]
> > 研究生复试，黑皮书看不懂，要靠这个救命了
> 
> 十分抱歉，关于黑书后面部分对软件测试和软件管理的介绍，学院的课纲里不采用黑书，我们也才开始学。给你找了份学校软件测试的材料不知道能不能派上用场，不过也只是和黑书对应内容相似。链接: https://pan.baidu.com/s/1asPkwkWD-Tm7Gi3TU9VtmA 提取码: m384

谢谢谢谢，非常感谢！
